# Generated by Django 6.0.4 on 2026-05-08 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0002_delete_borrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='author',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='title',
        ),
        migrations.AddField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.book'),
        ),
    ]
