# Generated by Django 6.0.4 on 2026-05-09 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_borrow_author_remove_borrow_title_borrow_book'),
        ('products', '0002_delete_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='borrow',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.book'),
        ),
    ]
