# Generated by Django 6.0.4 on 2026-05-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_borrow_penalty_borrow_returned_at_alter_borrow_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='penalty',
            new_name='blocked_days',
        ),
        migrations.AddField(
            model_name='borrow',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='notification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='sanction_applied',
            field=models.BooleanField(default=False),
        ),
    ]
