# Generated by Django 6.0.4 on 2026-05-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrow',
        ),
    ]
