# Generated by Django 6.0.3 on 2026-04-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
